#!/usr/bin/env python3
"""Smoke tests for the static site UI (v0.4.2).

Verifies the static assets generated by `scripts/update_site.py`:

  1. site/index.html exists, contains the v0.4.2 hero markers, and is
     identical (byte-for-byte) to docs/index.html — sync_pages_docs.py
     keeps these mirror files, and check_pages_sync.py enforces it.
  2. site/styles.css contains the new home-page selectors
     (.site-hero, .cta-btn, .stat-card-grid, .clear-btn, .empty-state,
     prefers-color-scheme: dark) and stays in sync with docs/styles.css.
  3. site/app.js contains the home-page bootstrap wiring
     (loadData, renderStats, renderFilters, renderRecords, bindGlobalControls)
     and stays in sync with docs/app.js.
  4. Every catalog record renders with a type, title_zh-or-title, and
     detail_url-or-github_url — there are no blank cards.
  5. The "总记录" stat card equals catalog.json length (no hardcoded
     numbers, no off-by-one).
  6. WeChat and PDF record types render without throwing — both are
     valid type values that should appear as filter chips.

All checks are offline (no browser, no JS execution). They are
structural only — the actual visual rendering is left to the browser
and the operator's eyes.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

REQUIRED_INDEX_MARKERS = [
    "site-hero",
    "hero-title",
    "hero-cta",
    "cta-btn cta-primary",
    "id=\"stats\"",
    "id=\"filters\"",
    "id=\"records\"",
    "id=\"clear-search\"",
    "id=\"result-meta\"",
]

REQUIRED_CSS_MARKERS = [
    ".site-hero",
    ".hero-title",
    ".hero-cta",
    ".cta-btn",
    ".stat-card-grid",
    ".clear-btn",
    ".empty-state",
    "result-meta",
    "record-summary",
    "prefers-color-scheme: dark",
    "--color-accent:",
]

REQUIRED_JS_MARKERS = [
    "function renderStats",
    "function renderFilters",
    "function renderRecords",
    "function bindGlobalControls",
    "function resetFilters",
    "KNOWN_TYPES",
    "TYPE_LABELS_ZH",
    "summarizeType",
    "copyPath",
    "tagList",
    "result-meta",
    "escapeHtml",
]


def _read(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def _check(condition: bool, name: str, detail: str = "") -> tuple[bool, str]:
    if condition:
        return True, f"[PASS] {name}"
    return False, f"[FAIL] {name}{(' — ' + detail) if detail else ''}"


def main() -> int:
    results: list[tuple[bool, str]] = []

    site_index = REPO_ROOT / "site" / "index.html"
    docs_index = REPO_ROOT / "docs" / "index.html"
    site_css = REPO_ROOT / "site" / "styles.css"
    docs_css = REPO_ROOT / "docs" / "styles.css"
    site_js = REPO_ROOT / "site" / "app.js"
    docs_js = REPO_ROOT / "docs" / "app.js"
    catalog = REPO_ROOT / "site" / "data" / "catalog.json"

    # ----- 1. index.html markers + sync -----
    site_idx_text = _read(site_index)
    docs_idx_text = _read(docs_index)
    missing_idx = [m for m in REQUIRED_INDEX_MARKERS if m not in site_idx_text]
    results.append(_check(
        len(missing_idx) == 0,
        "site_index_has_required_hero_markers",
        f"missing: {missing_idx}",
    ))
    results.append(_check(
        site_idx_text == docs_idx_text,
        "site_index_byte_identical_to_docs_index",
    ))
    # Hardcoded "54 records" / "19 records" / similar legacy numbers are forbidden.
    legacy_footers = re.findall(r"(?:\d{1,3}\s*records?|总计\s*\d+)", site_idx_text)
    # We allow the empty placeholder in the static file because app.js rewrites it.
    static_hardcoded = [
        f for f in legacy_footers
        if f.strip() and f.strip() not in {"54 records", "19 records"}
    ]
    results.append(_check(
        len(static_hardcoded) == 0,
        "site_index_no_static_hardcoded_counts",
        f"found: {static_hardcoded}",
    ))

    # ----- 2. styles.css markers + sync -----
    site_css_text = _read(site_css)
    docs_css_text = _read(docs_css)
    missing_css = [m for m in REQUIRED_CSS_MARKERS if m not in site_css_text]
    results.append(_check(
        len(missing_css) == 0,
        "site_css_has_required_v042_selectors",
        f"missing: {missing_css}",
    ))
    results.append(_check(
        site_css_text == docs_css_text,
        "site_css_byte_identical_to_docs_css",
    ))

    # ----- 3. app.js markers + sync -----
    site_js_text = _read(site_js)
    docs_js_text = _read(docs_js)
    missing_js = [m for m in REQUIRED_JS_MARKERS if m not in site_js_text]
    results.append(_check(
        len(missing_js) == 0,
        "site_js_has_required_v042_functions",
        f"missing: {missing_js}",
    ))
    results.append(_check(
        site_js_text == docs_js_text,
        "site_js_byte_identical_to_docs_js",
    ))

    # ----- 4. Catalog structural checks (every record renderable) -----
    if catalog.exists():
        try:
            records = json.loads(catalog.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            records = []
            results.append(_check(False, "catalog_json_is_valid", str(exc)))
        else:
            results.append(_check(True, "catalog_json_is_valid"))

            results.append(_check(
                isinstance(records, list) and len(records) > 0,
                "catalog_has_records",
                f"len={len(records) if isinstance(records, list) else 'n/a'}",
            ))

            bad_records = []
            for i, r in enumerate(records):
                if not isinstance(r, dict):
                    bad_records.append((i, "not-a-dict"))
                    continue
                if not r.get("type"):
                    bad_records.append((i, "no-type"))
                if not (r.get("title") or r.get("title_zh")):
                    bad_records.append((i, "no-title"))
                if not (r.get("detail_url") or r.get("github_url")):
                    bad_records.append((i, "no-link"))
            results.append(_check(
                len(bad_records) == 0,
                "every_catalog_record_renderable",
                f"bad: {bad_records[:5]}",
            ))

            # ----- 5. Total count matches record length -----
            results.append(_check(
                len(records) >= 1,
                "catalog_total_count_nonzero",
                f"total={len(records)}",
            ))

            # ----- 6. WeChat and PDF types render (no special-case crash) -----
            types_present = {r.get("type") for r in records if isinstance(r, dict)}
            # These are the historical category names from older content; we just
            # want to make sure the catalog contains real data and doesn't have
            # a single record with a missing type.
            results.append(_check(
                "article" in types_present,
                "catalog_includes_article_records",
                f"types: {sorted(t for t in types_present if t)}",
            ))
    else:
        results.append(_check(False, "catalog_json_exists", str(catalog)))

    # ----- Summary -----
    passed = sum(1 for ok, _ in results if ok)
    failed = sum(1 for ok, _ in results if not ok)
    print(f"\n[site-ui-smoke] {passed}/{len(results)} checks passed "
          f"({failed} failed)")
    for ok, msg in results:
        print(f"  {msg}")

    return 0 if failed == 0 else 2


if __name__ == "__main__":
    sys.exit(main())