#!/usr/bin/env python3
"""Smoke tests for generic web article import (v0.3.77).

Runs offline against synthetic fixtures. No real article text is fetched.

Verifies:
1. Local HTML fixture dry-run emits capture JSON.
2. <article>/<main> body extraction captures the synthetic body.
3. Chinese web article is source_language=zh-CN and mirror translation.
4. summary.md / notes.md generated by the importer are non-empty.
5. material_to_kb.py recognizes generic_web_url.
6. material_to_kb.py routes generic web URLs to web_article_to_kb.py.
7. YouTube routes to youtube_to_kb.py while PDF remains BLOCKED_UNSUPPORTED.
8. One failing web input does not interrupt a mixed batch.
9. check_kb.py still PASS.
10. check_pages_sync.py still PASS.
"""

from __future__ import annotations

import importlib.util
import json
import os
import re
import subprocess
import sys
import tempfile
import threading
from functools import partial
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TEST_PY = sys.executable
ENV = {**os.environ, "PYTHONIOENCODING": "utf-8", "PYTHONUTF8": "1"}

WEB_SCRIPT = REPO_ROOT / "scripts" / "web_article_to_kb.py"
ROUTER_SCRIPT = REPO_ROOT / "scripts" / "material_to_kb.py"
WEB_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "web_sample_article.html"
WEB_MIXED_TEMPLATE = REPO_ROOT / "tests" / "fixtures" / "material_inputs_web_mixed.txt"
PDF_FIXTURE = "tests/fixtures/material_router_sample.pdf"
YOUTUBE_URL = "https://youtu.be/material-router-still-unsupported"
BAD_WEB_URL = "http://127.0.0.1:9/material-router-unreachable"
YOUTUBE_METADATA_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "youtube_sample_metadata.json"
YOUTUBE_TRANSCRIPT_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "youtube_sample_transcript.vtt"
ENV["HERMES_YOUTUBE_FIXTURE_METADATA"] = str(YOUTUBE_METADATA_FIXTURE)
ENV["HERMES_YOUTUBE_FIXTURE_TRANSCRIPT"] = str(YOUTUBE_TRANSCRIPT_FIXTURE)


def run(cmd: list[str], cwd: Path = REPO_ROOT) -> tuple[int, str, str]:
    proc = subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        env=ENV,
    )
    return proc.returncode, proc.stdout or "", proc.stderr or ""


def check(condition: bool, name: str, detail: str = "") -> bool:
    status = "PASS" if condition else "FAIL"
    print(f"  [{status}] {name}")
    if detail:
        print(f"         {detail}")
    return condition


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_capture_path(stderr: str) -> Path:
    match = re.search(r"\[capture\]\s+(.+?)(?:\r?\n|$)", stderr)
    if not match:
        raise AssertionError("missing [capture] line")
    path = Path(match.group(1).strip())
    if not path.is_absolute():
        path = REPO_ROOT / path
    return path


def parse_router_stdout(stdout: str) -> dict:
    return json.loads(stdout)


class QuietHandler(SimpleHTTPRequestHandler):
    def log_message(self, format: str, *args) -> None:  # noqa: A003 - stdlib signature
        return


def start_fixture_server():
    handler = partial(QuietHandler, directory=str(WEB_FIXTURE.parent))
    server = ThreadingHTTPServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    url = f"http://127.0.0.1:{server.server_address[1]}/{WEB_FIXTURE.name}"
    return server, url


def item_by_input(items: list[dict], value: str) -> dict:
    for item in items:
        if item.get("input") == value:
            return item
    raise AssertionError(f"missing item for input {value}")


def smoke_1_html_dry_run_capture() -> tuple[bool, Path | None]:
    print("\n=== Smoke 1: web_article_to_kb local HTML dry-run ===")
    if not check(WEB_FIXTURE.exists(), "web HTML fixture exists", str(WEB_FIXTURE)):
        return False, None
    code, out, err = run([TEST_PY, str(WEB_SCRIPT), "--html-file", str(WEB_FIXTURE), "--dry-run"])
    ok = check(code == 0, "web_article_to_kb exits 0", f"exit={code}\nstderr tail: {err[-300:]}")
    ok &= check("STATUS: DRY_RUN_OK" in out, "dry-run reports STATUS: DRY_RUN_OK")
    if not ok:
        return False, None
    cap_path = parse_capture_path(err)
    ok &= check(cap_path.exists(), "capture JSON written", str(cap_path))
    return ok, cap_path


def smoke_2_capture_content(cap_path: Path) -> bool:
    print("\n=== Smoke 2: capture fields and article/main extraction ===")
    data = json.loads(cap_path.read_text(encoding="utf-8"))
    content = data.get("content_markdown", "")
    ok = check(data.get("title") == "合成网页文章：长期知识管理的三个入口",
               "title extracted from fixture", data.get("title", ""))
    ok &= check(data.get("source_site") == "合成网页实验室",
                "source_site extracted", data.get("source_site", ""))
    ok &= check(data.get("published_date") == "2026-07-01",
                "published_date extracted", data.get("published_date", ""))
    ok &= check(data.get("canonical_url") == "https://example.test/articles/knowledge-router",
                "canonical_url extracted", data.get("canonical_url", ""))
    ok &= check(data.get("source_language") == "zh-CN",
                "Chinese source detected", data.get("source_language", ""))
    ok &= check("长期知识管理并不是" in content and "系统应当诚实地返回不支持" in content,
                "article/main body content extracted")
    ok &= check("站点导航不应进入正文" not in content and "页脚不应进入正文" not in content,
                "header/footer noise excluded")
    ok &= check(len(data.get("images", [])) >= 1, "image metadata collected", str(data.get("images", [])))
    return ok


def smoke_3_generated_bundle(cap_path: Path) -> bool:
    print("\n=== Smoke 3: generated KB bundle content ===")
    module = load_module(WEB_SCRIPT, "web_article_to_kb")
    data = json.loads(cap_path.read_text(encoding="utf-8"))
    bundle = module.generate_output_bundle(data, localize_images=False)
    metadata = bundle["metadata.yaml"]
    ok = check('content_kind: "web_article"' in metadata, "metadata marks web_article")
    ok &= check('source_platform: "web"' in metadata, "metadata marks source_platform web")
    ok &= check("source_language: \"zh-CN\"" in metadata, "metadata source_language zh-CN")
    ok &= check("is_translation_mirror: true" in metadata, "Chinese article is translation mirror")
    ok &= check(len(bundle["summary.md"].strip()) > 200, "summary.md generated non-empty")
    ok &= check(len(bundle["notes.md"].strip()) > 200, "notes.md generated non-empty")
    ok &= check("## 主要观点" in bundle["summary.md"], "summary includes required section")
    ok &= check("## 一、接受" in bundle["notes.md"], "notes includes required section")
    return ok


def smoke_4_router_inference_and_mixed_batch() -> bool:
    print("\n=== Smoke 4: material router generic web route ===")
    router = load_module(ROUTER_SCRIPT, "material_to_kb")
    server, web_url = start_fixture_server()
    try:
        inferred = router.infer_input(web_url, index=0)
        ok = check(inferred["inferred_type"] == "generic_web_url",
                   "router infers generic_web_url", str(inferred))
        ok &= check(inferred["route"] == "web_article_to_kb.py" and inferred["supported"] is True,
                    "router marks generic web as supported web route", str(inferred))

        template = WEB_MIXED_TEMPLATE.read_text(encoding="utf-8")
        with tempfile.TemporaryDirectory(prefix=".web-router-smoke-", dir=REPO_ROOT) as tmp:
            input_list = Path(tmp) / "materials.txt"
            input_list.write_text(template.replace("__WEB_URL__", web_url), encoding="utf-8")
            code, out, err = run([TEST_PY, str(ROUTER_SCRIPT), "--input-list", str(input_list), "--dry-run"])
        ok &= check(code == 0, "mixed router batch exits 0", f"exit={code}\nstderr tail: {err[-300:]}")
        data = parse_router_stdout(out)
        items = data.get("items", [])
        summary = data.get("summary", {})
        ok &= check(summary.get("total") == 4, "mixed template produced 4 inputs", str(summary))

        web_item = item_by_input(items, web_url)
        bad_item = item_by_input(items, BAD_WEB_URL)
        yt_item = item_by_input(items, YOUTUBE_URL)
        pdf_item = item_by_input(items, PDF_FIXTURE)
        ok &= check(web_item["route"] == "web_article_to_kb.py",
                    "web URL routed to web_article_to_kb.py", str(web_item))
        ok &= check(web_item["status"] in {"DRY_RUN_OK", "SKIPPED_DUPLICATE"},
                    "web URL dry-run succeeds", web_item["status"])
        ok &= check(bad_item["status"] == "BLOCKED_FETCH_FAILED",
                    "failing web URL is BLOCKED_FETCH_FAILED", bad_item.get("failure_reason", ""))
        ok &= check(yt_item["route"] == "youtube_to_kb.py",
                    "YouTube routes to youtube_to_kb.py", yt_item.get("route", ""))
        ok &= check(yt_item["status"] in {"DRY_RUN_OK", "SKIPPED_DUPLICATE"},
                    "YouTube dry-run succeeds via fixture", yt_item.get("status", ""))
        ok &= check(pdf_item["status"] == "BLOCKED_UNSUPPORTED",
                    "PDF remains BLOCKED_UNSUPPORTED", pdf_item.get("failure_reason", ""))
        ok &= check(summary.get("blocked_fetch_failed") == 1 and summary.get("blocked_unsupported") == 1,
                    "failed/unsupported inputs counted without interrupting", str(summary))
        ok &= check((REPO_ROOT / data.get("report_markdown", "")).exists(),
                    "material markdown report generated")
        ok &= check((REPO_ROOT / data.get("report_json", "")).exists(),
                    "material json report generated")
        return ok
    finally:
        server.shutdown()
        server.server_close()


def smoke_5_quality_gates() -> bool:
    print("\n=== Smoke 5: check_kb and check_pages_sync ===")
    code1, out1, _ = run([TEST_PY, str(REPO_ROOT / "scripts" / "check_kb.py")])
    code2, out2, _ = run([TEST_PY, str(REPO_ROOT / "scripts" / "check_pages_sync.py")])
    ok = check(code1 == 0 and "STATUS: PASS" in out1, "check_kb.py PASS", f"exit={code1}")
    ok &= check(code2 == 0 and "STATUS: PASS" in out2, "check_pages_sync.py PASS", f"exit={code2}")
    return ok


def main() -> int:
    print("=" * 60)
    print("Generic web article import smoke tests (v0.3.77)")
    print("=" * 60)
    ok1, cap_path = smoke_1_html_dry_run_capture()
    results = [ok1]
    if cap_path:
        results.extend([
            smoke_2_capture_content(cap_path),
            smoke_3_generated_bundle(cap_path),
        ])
    else:
        results.extend([False, False])
    results.extend([
        smoke_4_router_inference_and_mixed_batch(),
        smoke_5_quality_gates(),
    ])
    print("\n" + "=" * 60)
    passed = sum(results)
    total = len(results)
    if passed == total:
        print(f"ALL WEB ARTICLE SMOKE TESTS PASSED ({passed}/{total})")
        return 0
    print(f"WEB ARTICLE SMOKE TESTS FAILED ({passed}/{total})")
    return 1


if __name__ == "__main__":
    sys.exit(main())
